### ISSUE TITLE
Check most recent user verification is within maxVerifiedTime in contract

### ISSUE THREAD

**Issue by HughParry** [prosopo/captcha#782] opened 2023-11-09 17:00 UTC

**Comment by HughParry** [comment] 2023-11-09 17:08
When contract is queried like so:

```
(await contractApi.query.dappOperatorIsHumanUser(user, this.config.solutionThreshold)).value
                .unwrap()
                .unwrap()
```

We need to be able to supply it with a maxVerifiedTime, such that the contract checks the user's score and make sure they have completed a captcha within maxVerifiedTime

**Comment by forgetso** [comment] 2023-11-09 18:55
We might be able to use the exising function below for this

```
        /// Get the last correct captcha for a user
        #[ink(message)]
        pub fn dapp_operator_last_correct_captcha(
```

**Comment by HughParry** [comment] 2023-11-16 09:09
Addressed by this pr https://github.com/prosopo/captcha/pull/780

**Comment by goastler** [comment] 2023-11-16 10:37
#445 related

**Comment by forgetso** [comment] 2023-11-16 10:37
Duplicate of #445

**Closed by forgetso** 2023-11-16 10:37 UTC
Labels: contract
