### ISSUE TITLE
change terminology throughout

### ISSUE THREAD

**Issue by goastler** [prosopo/captcha#244] opened 2023-07-12 14:59 UTC

**Comment by goastler** [comment] 2023-07-12 14:59
- dapp_user -> user

anything else?

**Comment by goastler** [comment] 2023-07-12 15:12
prosopo/captcha#172

**Comment by goastler** [comment] 2023-07-13 09:29
- captcha_solution_commitment -> commit
- dapp -> app
- operator -> admin

**Comment by HughParry** [comment] 2023-11-16 09:51
Note:

e.g. contract has dappAccount whereas js has dapp

"[rename JS contract variables to match](https://github.com/prosopo/captcha/issues/172)"

**Comment by HughParry** [comment] 2023-11-16 09:52
Note:

[Change contract to account in dapp_register, DappConfig and other locations](https://github.com/prosopo/captcha-private/issues/636)

**Comment by HughParry** [comment] 2023-11-16 10:49
Need to agree on terminology as team before changes

**Comment by HughParry** [comment] 2024-06-13 20:22
Closing since very old, dupe of https://github.com/prosopo/captcha/issues/172, needs refinement (what terminology needs changing), etc

**Comment by HughParry** [comment] 2024-06-14 12:58
Didn't mean to reopen this

**Closed as completed by HughParry** 2024-06-14 12:58 UTC
Labels: documentation
