### ISSUE TITLE
Unexpected identifier 'assert'

### ISSUE THREAD

**Issue by hckhanh** [prosopo/captcha#1539] opened 2024-11-21 14:06 UTC
I get this bug:

```sh
21:05:30 [ERROR] Unexpected identifier 'assert'
  Stack trace:
    at compileSourceTextModule (node:internal/modules/esm/utils:338:16)
    at #translate (node:internal/modules/esm/loader:437:12)
```

 when I try to use `@prosopo/procaptcha-react` with Astro

```tsx
import { Procaptcha as BaseProcaptcha } from '@prosopo/procaptcha-react'
import { ProcaptchaConfigSchema } from '@prosopo/types'

const config = ProcaptchaConfigSchema.parse({
  account: {
    address: '5D9hogmbJrSvxVK96jGNS3BJceMnvZ1MyWWuSCRYcii7zQtH',
  },
  // web2: 'true',
  // dappName: 'client-example',
  // defaultEnvironment: 'rococo',
})

export function Procaptcha() {
  return <BaseProcaptcha config={config} />
}
```

**Comment by forgetso** [comment] 2024-11-21 14:09
Hey @hckhanh, thanks for reporting. Are you using [Node 22](https://stackoverflow.com/questions/78876691/syntaxerror-unexpected-identifier-assert-on-json-import-in-node-v22)? This might be the cause for the issue. We are building against Node 20.

Also, @prosopo/procaptcha-react is image captcha only. Is this what you wanted?

[@prosopo/procaptcha-frictionless](https://www.npmjs.com/package/@prosopo/procaptcha-frictionless) will dynamically serve either a Proof-of-Work captcha or an image captcha if the user is likely to be a bot.

**Comment by hckhanh** [comment] 2024-11-21 14:19
Hi @forgetso, I just follow the docs to getting started. I will try [@prosopo/procaptcha-frictionless](https://www.npmjs.com/package/@prosopo/procaptcha-frictionless) instead. I am using Node v23

**Comment by hckhanh** [comment] 2024-11-21 14:29
So I have to downgrade to Node v20 to use this package right? @forgetso

**Comment by forgetso** [comment] 2024-11-21 21:37
Hi @hckhanh, that's correct for now, sorry! We do have plans to upgrade Node in the near future but we're not quite there yet. Happy to accept PRs!

Please let me know if you need any more assistance.

**Comment by HughParry** [comment] 2024-12-03 13:17
Closing since we now have support for node 20+

Support for node 18 and below should now be deprecated

**Closed as completed by HughParry** 2024-12-03 13:17 UTC
